from typing import Protocol, List, Dict, Any


class PersistencePort(Protocol):
    """Puerto de persistencia. Define operaciones agnósticas al mecanismo de almacenamiento."""

    # History
    def load_history(self) -> List[Dict[str, Any]]: ...
    def save_history(self, history: List[Dict[str, Any]]) -> None: ...

    # Active positions
    def load_active_positions(self) -> Dict[str, Dict[str, Any]]: ...
    def save_active_positions(self, active: Dict[str, Dict[str, Any]]) -> None: ...

    # Account
    def load_account(self) -> Dict[str, Any]: ...
    def save_account(self, account: Dict[str, Any]) -> None: ...

    # Bot status
    def load_bot_status(self) -> Dict[str, bool]: ...
    def save_bot_status(self, status: Dict[str, bool]) -> None: ...


